version: 2
jobs:
  build:
    working_directory: ~/remvee/exifr
    parallelism: 1
    shell: /bin/bash --login
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    docker:
    - image: circleci/build-image:ubuntu-14.04-XXL-upstart-1189-5614f37
      command: /sbin/init
    steps:
    - checkout
    - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS

    - restore_cache:
        keys:
        - v1-dep-{{ .Branch }}-
        - v1-dep-master-
        - v1-dep-

    - run: rvm get head || true
    - run: rvm 1.8.7,1.9,2.3,2.4,2.5,2.6,jruby-1.7,jruby-9.1,jruby-9.2 do bundle install || true

    - save_cache:
        key: v1-dep-{{ .Branch }}-{{ epoch }}
        paths:
        - ~/.bundle
        - ~/.rvm
        - /opt/circleci/.rvm/
        - /opt/circleci/ruby/

    - run: rvm 1.8.7,1.9,2.3,2.4,2.5,2.6,jruby-1.7,jruby-9.1,jruby-9.2 do rake test

    - store_test_results:
        path: /tmp/circleci-test-results
    - store_artifacts:
        path: /tmp/circleci-artifacts
    - store_artifacts:
        path: /tmp/circleci-test-results
